from lichess_client.endpoints.account import Account
from lichess_client.endpoints.broadcast import Broadcast
from lichess_client.endpoints.challenges import Challenges
from lichess_client.endpoints.chess_bot import ChessBot
from lichess_client.endpoints.games import Games
from lichess_client.endpoints.messaging import Messaging
from lichess_client.endpoints.relations import Relations
from lichess_client.endpoints.simulations import Simulations
from lichess_client.endpoints.studies import Studies
from lichess_client.endpoints.teams import Teams
from lichess_client.endpoints.tournaments import Tournaments
from lichess_client.endpoints.users import Users
from lichess_client.endpoints.bots import Bots
from lichess_client.endpoints.boards import Boards
