name: Build add-on

on:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: python -m pip install scons Markdown
      - name: Build add-on file
        run: scons
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chessmart.nvda-addon
          path: *.nvda-addon